services:
  core:
    image: ci
    build:
      args:
        - UID=${HOST_UID-1000}
        - GID=${HOST_GID-1000}
        - PROJECT_NAME=${PROJECT_NAME_ENV}
        - RUN_POETRY_INSTALL_AT_BUILD_TIME=true
      context: ../../
      dockerfile: environments/Dockerfile
    tty: true
    volumes:
        - ../../:/home/challenger/${PROJECT_NAME_ENV}
